package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Configuration.baseUrl;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GogWebTests extends TestBase {


    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.gog.com/'", () ->
            open(baseUrl));

        step("Page title should have text 'GOG.com'", () -> {
            String expectedTitle = "GOG.com";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.gog.com/'", () ->
                open(baseUrl));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }

    @Test
    @Description("Раздел Магазин")
    @DisplayName("открыть раздел Магазин")
    void generatedTest() {
        step("open https://www.gog.com/", () -> {
            open(baseUrl);
            $(".menu__container").$(".menu-main").$(".js-menu-link").click();

        });
    }

    @Test
    @Description("Раздел Магазин")
    @DisplayName("Открыть раздел Новые игры")
    void openNewGamesTab () {
        step("find New games tab", () -> {
            open(baseUrl);
            $(".menu__container").$(".menu-main").$(".js-menu-link").hover();
            $(".menu-store__submenu")
                    .$(".menu-submenu-link--featured[hook-test='storeMenunew-releasesButton']").click();
        });

        step("Проверка, что вошли в раздел Новые игры", () ->
            $("#catalogHeader").shouldHave(Condition.text("Новые игры"))
        );
    }
    @Test
    @Description("Раздел Магазин")
    @DisplayName("Проверить раскрывающееся окно с играми в подразделе Приключения")
    void gamesSubWindow () {
        step("Открыть сайт", () ->
                open(baseUrl));
        $(".menu__container").$(".menu-main").$(".js-menu-link").hover();
        $(".menu-store__submenu").$(".menu-section-layer").sibling(7).hover();
        $(".menu-section-layer--adventure").shouldHave(Condition.text("приключения"));
    }

    @Test
    @Description("Раздел Поддержка")
    @DisplayName("Зайти в раздел Заказы и оплата")
    void ordersAndPaymentTab () {
        step("Открыть сайт", () ->
                open(baseUrl));
        step("Раскрыть раздел Поддержка", () ->
                $(".menu-main").$(".js-menu-support").hover());
        step("Перейти в раздел Заказы и оплата", () ->
                $(".js-menu-support")
                        .$("a[href*='https://support.gog.com/hc/ru/categories/201552965?product=gog']")
                        .click()
                );
        step("Проверка, что зашл в раздел Заказы и оплата", () ->
                $(".page-header").$("h1.h2")
                        .shouldHave(Condition.text("ЗАКАЗ И ОПЛАТА")));
    }
    @Test
    @Description("Поиск")
    @DisplayName("Проверть работу поиска после ввода названия игры")
    void someGameSearch () {
        step("Открыть сайт", () ->
                open(baseUrl));
        step("Открыть поиск и ввести название игры", () -> {
        $(".menu__container").$(".js-menu-search").click();
        $(".menu-search-input").click();
        $(".menu-search-input__field").setValue("neverwinter nights");
        });
        step("Проверка наличия искомой игры", () ->
        $(".menu-search__results-list").shouldHave(Condition.text("neverwinter nights")));
    }
}